### ISSUE TITLE
commands for all existing item meta

### ISSUE THREAD

**Issue by TehBrian** [TehBrian/Iteminator#11]
- [x] ArmorStand
- [x] AxolotlBucket
- [x] Banner
- ~~BlockData~~ (impractical)
- ~~BlockState~~ (impractical)
- [ ] Book (lacking page subcommands)
- ~~Bundle~~ (useless)
- ~~Compass~~ (useless)
- ~~Crossbow~~ (useless)
- [x] Damageable
- [x] EnchantmentStorage
- [ ] Firework (lacking firework effect subcommands)
- [ ] FireworkEffect (lacking full color/fade color support)
- ~~KnowledgeBook~~ (not planned)
- [x] LeatherArmor
- [x] Map
- [x] Potion
- [x] Repairable
- [x] Skull
- [x] SuspiciousStew
- [x] TropicalFishBucket

**Comment by TehBrian** [comment]
ACTUALLY FCK ALL THIS CUZ DATA COMPONENTS WOOOOOOOOOOOOOOOOOOO

the checklist is still helpful tho
